#!/bin/bash

#for d in src/http/*; do cd $d && npm i --no-save uuid && cd -; done

echo "Generating Sam"
npx arc deploy production --dry-run

echo "Injecting metadata and environment variables"
npm run inject

echo "Packaging template"
AWS_PROFILE=ft sam package --template-file sam.json --output-template-file template.yaml --s3-bucket micro-s3-upload-template --force-upload

echo "Publishing package"
AWS_PROFILE=ft sam publish --template template.yaml --region us-east-1
