# generator-arc version: 2.1.1

name: micro s3 upload Destroy

on:
  pull_request:
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: chrislennon/action-aws-cli@v1.1
    - name: aws creds
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure --profile sgff set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure --profile sgff set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - name: Remove
      if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      id: remove
      continue-on-error: true
      run: |
        BRANCHRAW=micro-s3-upload-$(echo ${{ github.head_ref }})
        BRANCH=$(echo $BRANCHRAW | sed -E 's|refs/[a-zA-Z]+/||')
        STACK_NAME=$(echo $BRANCH | sed -r 's/(^|-)(\w)/\U\2/g')Staging
        BUCKET=$(aws cloudformation describe-stacks --region=us-east-1 --profile=sgff --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='BucketURL'].OutputValue" --output text | awk -F/ '{sub(/^www\.micro-s3-upload?/,"",$3); print $3}' | awk -F"." '{print $1}')
        echo ::set-output name=stack_name::$STACK_NAME
        echo ::set-output name=bucket::$BUCKET
        aws cloudformation delete-stack --profile=sgff --region=us-east-1 --stack-name $STACK_NAME
    - name: Status Color
      if: always() && github.ref != 'refs/heads/master' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      id: statuscolor
      run: |
        STATUS_COLOR=$([ ${{ job.status }} == 'Success' ] && echo '#2ECC71' || echo '#E74C3C')
        echo ::set-output name=status_color::$STATUS_COLOR
    - name: Slack Notification
      if: always() && github.ref != 'refs/heads/master' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      uses: 8398a7/action-slack@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      with:
        status: custom
        payload: |
          {
            text: "micro s3 upload | Cleanup",
            attachments: [{
              "author_name": "micro s3 upload Production", // json
              fallback: 'fallback',
              color: '${{ steps.statuscolor.outputs.status_color }}',
              title: 'Status',
              text: '${{ job.status }}',
              fields: [{
                title: 'Stack Name',
                value: '${{ steps.remove.outputs.stack_name }}',
                short: true
              }, {
                title: 'Bucket',
                value: '${{ steps.remove.outputs.bucket }}',
                short: true
              }],
              actions: [{
              }]
            }]
          }

